### ISSUE TITLE
Article Filter 대문자 검색 이슈

### ISSUE THREAD

**Issue by gwansikk** [emewjin/emewjin.github.io#10]
안녕하세요 emewjin님,

먼저 블로그의 유용한 정보에 대해 감사드립니다. 항상 좋은 내용으로 많은 도움을 받고 있어요! 😄
아티클 필터로 검색하다가 소문자로 검색할 때는 문제없이 필터링이 되는 반면, 대문자로 검색할 경우 필터링이 제대로 작동하지 않는 버그를 발견했습니다. 의도된 기능일지 몰라 이슈를 남기게 되었습니다. 소중한 시간을 내어 확인해주시면 감사하겠습니다!

## 이슈 재현

아래 이미지에서 보이듯이, 대문자로 검색했을 때는 검색 결과가 나타나지 않습니다. 

| <img width="750" alt="image" src="https://github.com/emewjin/emewjin.github.io/assets/39869096/f88d9af5-4d22-4ad3-8cae-ba715af5f40c"> | <img width="722" alt="image" src="https://github.com/emewjin/emewjin.github.io/assets/39869096/8417b467-ea95-45a7-a7af-d90e54162d4e"> |
| :-----------------------------------------------------------------------------------------------------------------------------------: | :-----------------------------------------------------------------------------------------------------------------------------------: |
|                                                                소문자                                                                 |                                                                대문자                                                                 |

## 원인 분석

```ts
export const filterPostsByTitle = (posts: Posts, title: string): Posts => {
  if (title === '') {
    return posts;
  }
  return posts.filter((post) => post.frontmatter?.title?.toLocaleLowerCase().includes(title));
};
```

`src/utils/filterPosts.ts`의 코드를 살펴보니, filter 함수에서 post.frontmatter?.title을 소문자로만 변환하여 검색하는 것을 확인했습니다. 이로 인해 대문자가 포함된 검색 쿼리에서 원하는 결과를 얻지 못하는 문제가 발생하는 것 같습니다.

검색 쿼리(해당 코드에선 title 변수)를 소문자로도 변환한다면 더 범용적이고 일관된 검색 결과를 얻을 수 있을 것 같습니다. 만약 바쁘시다면, 제가 해당 부분을 수정하여 PR을 올리도록 하겠습니다. ✨
감사합니다.

**Comment by emewjin** [comment]
안녕하세요! 바쁘신 와중에 이슈를 발견해주셔서 감사합니다 😊
제보해주신 이슈는 수정해두겠습니다 👍🏻 
추가로, 제 블로그는 https://github.com/blurfx/gatsby-starter-lavender 템플릿을 사용하고 있는데요!
만일 PR을 작성해주신다면 해당 템플릿 저장소로 PR을 날려주시면 저 뿐만 아니라 템플릿을 사용하는 많은 분들께도 도움이 될 것 같습니다ㅎㅎ
